### ISSUE TITLE
Bug in Excel MovingResponseOptions

### ISSUE THREAD

**Issue by drschr** [ianhussey/IRAP#8]
Hi Ian,

thanks for sharing the tool, this is really useful and I may actually modify it for my research! I found a small bug and just wanted to report it, because this prevented psychopy from starting the actual experiment on my psychopy (using 1.85.2), there was this error which was thrown after the second instruction screen:

"Traceback (most recent call last):
  File "C:\Users\schroeder\Downloads\OpenSourceIRAP-master(1)\OpenSourceIRAP-master\Open Source IRAP_lastrun.py", line 984, in <module>
    if string_to_booleanl(moving_response_options) == False:
  File "C:\Users\schroeder\Downloads\OpenSourceIRAP-master(1)\OpenSourceIRAP-master\Open Source IRAP_lastrun.py", line 81, in string_to_booleanl
    return v.lower() in ("yes", "true", "TRUE", "True", "t", "T", "1")
AttributeError: 'numpy.bool_' object has no attribute 'lower'"

Fix was simply to change the column moving_response_options value in the task excel file to something else such as "yes" or "no" (both would work on my computer). Ironically, this helper function provided in line 81 of the py script was there to "idiot-proof the excel files" but it could not handle the suggested correct naming of a boolean in the excel file (I found this funny but I also have a sort of weird humour sometimes); in the current version of the master-file, the value is "False" and I think that this value cannot be converted using the helper function because it is already a correct boolean object. 

Just hope this helps if someone else stumbles across the error! 

Best
Philipp

**Comment by ianhussey** [comment]
Hi Philipp,

Thanks for flagging this. I hadn't tried to track down the error that caused this in psychopy >1.82. Something was changed that made my idiotproofing stop working. I changed the data file to simply use a boolean and it now works in psychopy 1.85.3 (current).

I also changed the processing script to use an RMarkdown file with relative directories, so users don't have to manually point the script to their data.

Thanks for pointing this out,

Best
Ian
